### ISSUE TITLE
Code theft lol

### ISSUE THREAD

**Issue by afkvido** [ProdigyAPI/ProdigyXElectronApp#1]
The code in this line and the following few lines of:
https://github.com/ProdigyAPI/ProdigyXElectronApp/blob/8c8e34792641a14977c354c6470ff0d4a9238c41/src/app.ts#L19

Is a fucking ripoff of
https://github.com/LeoBadeaux/DPHA/blob/main/src/connection/stripper.js

**Comment by hostedposted** [comment]
Have you ever heard of using stackoverflow? https://stackoverflow.com/questions/59087869/electron-retrieving-http-response-headers-from-the-browserwindows-loadurl

Also of course the code is similar as it is the best way to do it. When you copy our hacks, you are doing things like deobfuscating it, or even just copying it. I don't copy code. If I were to copy code I would simply paraphrase it. Look at the code, then rewrite it without looking back at the code, so I would not have to copy it. Nonetheless, I don't copy code.

**Comment by afkvido** [comment]
> Have you ever heard of using stackoverflow?

Ofc, I use stackoverflow pretty often. Also, that link doesn't have the literal same exact code fragment as stripper.js.

<br>


Also, `When you copy our hacks, you are doing things like deobfuscating it, or even just copying it`- that's definetly cap. The only hack I "copied" was Get UserIDs of all players on screen. The concept of the "Max Account" hack was literally made by me. And about the deobfuscation, I'd gladly do it then show Prodigy and the world what y'all were up to in your suspicious lil hack.tsx.

Tho I'd like to say that ProdigyX has one thing on top of ProdigyPNP, and that's its structure, since y'all are using shit like React for your GUIs, which is something ProdigyPNP is yet to do. Tho pnp is fully open source + no ads.

**Comment by hostedposted** [comment]
By the way, I am working on a module for making cheat menu creation easier. It makes it so you can generate cheat menus with lots of structure and minimal bundle sizes easily. I'm expecting it to be done today or tomorrow.

**Comment by AgrTheDev** [comment]
> 

Why are you here creepy dyed hair kid… I thought you cheaply stealing our fix was gonna be the last appearance from you

**Comment by AgrTheDev** [comment]
Bro really saw one line and came to the conclusion it was copied 💀

**Comment by afkvido** [comment]
Not one line, in fact the entire stripper.js

**Comment by AgrTheDev** [comment]
> Not one line, in fact the entire stripper.js

Why don't you keep your head in your own business. Invalidly making claims (well ig ur used to it cuz you do it 24/7 in your server) on a repo with less then 50 views is wasting your own time.

**Comment by afkvido** [comment]
Alr
